# Install pre-commit hooks via
# pre-commit install

# black: automatic formatter
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    language_version: python3

# pylint: run from current env to find imported modules
- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: python -m pylint.__main__ --disable=fixme
    language: system
    types: [python]
    exclude: '^(tests/)|(docs/)|setup\.py'
