# Install pre-commit hooks via
# pre-commit install
 
# yapf = yet another python formatter
- repo: https://github.com/pre-commit/mirrors-yapf
  sha: v0.26.0
  hooks:
  - id: yapf

# pylint: THE python linter
- repo: https://github.com/pre-commit/mirrors-pylint
  rev: v2.3.1
  hooks:
  - id: pylint
