dist: bionic
language: python
python:
- '3.6'
- '3.7'
cache: pip
install:
- pip install .[pre-commit,testing,docs]
- pre-commit install --install-hooks
script:
- pre-commit run -a
- pytest -v --cov-report xml --cov-report term-missing --cov-append --cov aiida_gaussian_datatypes tests/
after_success:
- codecov
deploy:
  provider: pypi
  user: dev-zero
  password:
    secure: bSHHdPQiW0va/9UHLG8m/LzA2Vdc20MjAA9a/gZ+aSp6DqQEnOUzj8vDoVw7zTg3wWtHqY9Gd3SLzl89qUH3l7fIF31wVJ8M8O6blaFYK+R1KKc6J8DgZW1mMcxlnlrrWBbuAJTzMa1KJyF2JThTNr2skdbfnJeDJzTRL6xqLlIqGB1OUmNzy4PVefJHzUQ/OHz90ffG3YKY/zUzqCH098nkfWlRI2d3zMRhwcwA+7HQbc3iDBppwfBzhmizBTQAxAAQ3GWhZG5yB+f/hgEQaK15j7Hd5EYabfLuZRdibBVYtw8ANT4jLj1zmMZdUlzfCnpdC2mv22KJEqJXCiW0CFz2GFASjmcVlMa4g/1+ZKGGPmezCYh6GF47yErTSZ/RrhPhnEuepEp1md4YLZznfAt3iQWIAW1fng0+yy90wCYBrj//Xr0ry/OAKRRKvHJ6LSu8bez0L8agrm2MLCO9vW55LJrB2PMzT9Va+gE8FpNkuc7kPQhKoPl6rPnT0JhDCCV6YpoyKWU1NOUhn7/iRzso4e297jVbcHLI3GCziWLyvLgCU+S15/V6CsJxHsbfI8LsiYZ8RBU+aiCZtCNosT4p5ELg8iH9JlrUXQ03wLgduuKY43BMjR53rROuhXr8Ghb3QOTK4Vch05z4gE1tN9G9GzOMo1VaSesey71SoAI=
  on:
    tags: true
  distributions: sdist bdist_wheel
  skip_existing: true
